name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build ASP.NET Core
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore QE190088_SE19B_Ass1_BE.sln

      - name: Build
        run: dotnet build QE190088_SE19B_Ass1_BE.sln --configuration Release --no-restore